version: '3.2'

services:
  nginx:
    build:
      context: nginx/step7/
    volumes:
      - type: bind
        source: ./nginx/ssl/letsencrypt
        target: /etc/letsencrypt
    ports:
     - target: 443
       published: 443
       protocol: tcp
       mode: host
     - target: 80
       published: 80
       protocol: tcp
       mode: host
    restart: "on-failure:5"
  registry:
    restart: always
    image: registry:2
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/pwd
      REGISTRY_AUTH_HTPASSWD_REALM: registry.kitapp.org
    volumes:
     - type: bind
       source: ./datastore/fifth-db-path
       target: /var/lib/registry
     - type: bind
       source: ./nginx/auth
       target: /auth    

