version: '3.2'

services:
  nginx:
    build:
      context: nginx/step6/
    volumes:
      - type: bind
        source: ./nginx/ssl/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: ./nginx/auth/
        target: /auth/
    ports:
     - target: 443
       published: 443
       protocol: tcp
       mode: host
     - target: 80
       published: 80
       protocol: tcp
       mode: host
    restart: "on-failure:5"
  registry:
    restart: always
    image: registry:2
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    volumes:
     - type: bind
       source: ./datastore/fourth-db-path
       target: /var/lib/registry    
